# -*- coding: utf-8 -*-
"""Emit the drift-timeline figure as TikZ, computed from data/elements.json.

Hand-drawn figures go stale exactly the way hand-maintained numbers do, so this
generates the figure from the same file the API serves. Re-run it after any
timeline change and paste the output over the figure block in the paper.

    python scripts/make_figure.py > figure-drift.tex

Deliberately plain TikZ -- \\draw, \\node, \\fill and nothing else -- so it
compiles anywhere tikz is installed, with no pgfplots or library dependency.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EL = json.load(open(os.path.join(ROOT, "data", "elements.json"), encoding="utf-8"))

JUR = ["EN", "HK", "SG", "AU"]
X0, X1 = 1880, 2030          # data range, compressed below
WIDTH = 12.4                 # cm of drawing width
ROW = 0.42                   # cm between jurisdiction rows
PANEL_GAP = 1.55             # cm between timelines

# The events cluster in 1985-2030 with a few Victorian outliers. A linear axis
# would waste four fifths of the width, so compress everything before 1985 into
# the first eighth of the axis and keep the modern era linear.
BREAK = 1985


def x(year):
    if year <= BREAK:
        frac = (year - X0) / float(BREAK - X0) * 0.13
    else:
        frac = 0.16 + (year - BREAK) / float(X1 - BREAK) * 0.84
    return round(frac * WIDTH, 3)


def style(f):
    """Direction of travel for the claimant, as recorded in the timeline."""
    if f >= 0.45:
        return "fill=black"                       # strongly widens liability
    if f >= 0.05:
        return "fill=black!45"
    if f > -0.45:
        return "fill=white, draw=black!60"
    return "fill=white, draw=black!60, line width=0.7pt"   # strongly narrows


out = []
w = out.append
w("% GENERATED by scripts/make_figure.py -- do not edit by hand.")
w("\\begin{figure}[t]\\centering")
w("\\begin{tikzpicture}[x=1cm, y=1cm, font=\\scriptsize]")

y = 0.0
for tid in sorted(EL["timelines"]):
    tl = EL["timelines"][tid]
    w(f"  %% ---- {tid}: {tl.get('title_en', '')}")
    w(f"  \\node[anchor=west, font=\\scriptsize\\bfseries] at (0,{y + 0.52:.2f}) "
      f"{{{tid}. {tl.get('title_en','')}}};")

    present = {e["j"] for e in tl["events"]}
    for i, j in enumerate(JUR):
        yy = y - i * ROW
        w(f"  \\node[anchor=east, font=\\tiny] at (-0.12,{yy:.2f}) {{{j}}};")
        col = "black!15" if j in present else "black!7"
        w(f"  \\draw[{col}, line width=0.5pt] (0,{yy:.2f}) -- ({WIDTH},{yy:.2f});")
        if j not in present:
            w(f"  \\node[anchor=west, font=\\tiny, text=black!45] "
              f"at ({WIDTH + 0.08},{yy:.2f}) {{no authority}};")

    for e in tl["events"]:
        yy = y - JUR.index(e["j"]) * ROW
        w(f"  \\draw[{style(e['f'])}] ({x(e['y']):.3f},{yy:.2f}) circle (0.062);")

    y -= len(JUR) * ROW + PANEL_GAP

# axis
ax = y + PANEL_GAP - 0.45
w(f"  \\draw[black!45] (0,{ax:.2f}) -- ({WIDTH},{ax:.2f});")
for year in (1885, 1985, 2000, 2015, 2030):
    w(f"  \\draw[black!45] ({x(year):.3f},{ax:.2f}) -- ({x(year):.3f},{ax - 0.08:.2f});")
    w(f"  \\node[anchor=north, font=\\tiny] at ({x(year):.3f},{ax - 0.10:.2f}) {{{year}}};")
w(f"  \\node[anchor=north, font=\\tiny, text=black!55] at ({x(1930):.3f},{ax - 0.10:.2f}) "
  f"{{\\itshape axis compressed}};")

# legend
lg = ax - 0.62
w(f"  \\draw[fill=black] (0.10,{lg:.2f}) circle (0.062);")
w(f"  \\node[anchor=west, font=\\tiny] at (0.22,{lg:.2f}) {{widens liability}};")
w(f"  \\draw[fill=white, draw=black!60] (3.05,{lg:.2f}) circle (0.062);")
w(f"  \\node[anchor=west, font=\\tiny] at (3.17,{lg:.2f}) {{narrows it}};")
w("\\end{tikzpicture}")
w("\\caption{Test-changing decisions by jurisdiction, from the released "
  "timelines. Each mark is one decision; fill shows the direction of travel. "
  "The empty rows are coverage gaps, reported rather than interpolated. T3 is "
  "the inversion discussed in Section~\\ref{sec:drift}: Hong Kong adopts the "
  "deceit measure in 1991 and never wavers, while England, the source "
  "jurisdiction, doubts its own rule in 1996.}\\label{fig:drift}")
w("\\end{figure}")

print("\n".join(out))
